### ISSUE TITLE
I have some problem for MOBSF

### ISSUE THREAD

**Issue by wywlz** [ajinabraham/libsast#22]
My apps contain FFmpeg ，and the customer needs to add the relro safe compilation option to the ffmpeg library. After I added the option during compilation, I used linux's checksec to detect library and found that relro has been added. However, when I package library into the app and put it into mobsf for detection, mobsf reminds me that my library does not contain relro. Now I have no good way. I hope I can get help。

**Comment by ajinabraham** [comment]
You opened an issue on the wrong project.
