### ISSUE TITLE
deleting multiline comments does not work correctly

### ISSUE THREAD

**Issue by Skripko-Ivan** [ajinabraham/libsast#43]
Libsast pattern for deleting multiline comment ("/\*([\S|\s]+?)\*/") will delete code if it will find "/*" in constant string. For example:
uriMatcher.addURI(PROVIDER_NAME, "users/*", 1);

**Comment by ajinabraham** [comment]
What version of libast are you using? This is the comment detection regex: https://github.com/ajinabraham/libsast/blob/09165d63062312b6ecfef6fb96177851030c9d42/libsast/core_matcher/helpers.py#L18C26-L18C43

**Comment by Skripko-Ivan** [comment]
Github delete some symbols from my issue text.
Correct issue text:
Libsast pattern for deleting multiline comment ("/\*([\S|\s]+?)\*/") will delete code if it will find "/*" in constant string. For example:
uriMatcher.addURI(PROVIDER_NAME, "users/*", 1);
test = 2;
/* comment */
As result, it will delete:
/*", 1);
test = 2;
/* comment */

**Comment by ajinabraham** [comment]
Yeah this is a limitation of regex based approach,
It will match 
```
/*", 1);
test = 2;
/* comment */
```

Regex matches are are quick pattern lookups. You should use a semgrep rule with libsast instead to get better AST based look up.
