### ISSUE TITLE
Update SEMGREP version to support more languages

### ISSUE THREAD

**Issue by fraaaandelpino** [ajinabraham/libsast#44]
I am trying to introduce in my MobSF instance the [OWASP rules for mobile application analysis](https://github.com/mindedsecurity/semgrep-rules-android-security) I have already included the rules in the project and I have been testing for the included rules, I have some problems with some rules:
- The version of SEMGREP that the libsast uses is v0.117.0 which does not support XML language, this language is supported from version [v1.10.0](https://github.com/semgrep/semgrep/tree/v1.1.0) so seeing that the version of SEMGREP is quite simple and obsolete you could migrate to a much more recent version that supports more languages and not only Python, Java, JavaScript, Go and C as specified in the README.

**Comment by ajinabraham** [comment]
Done
